"""
Regression check for the LALAS representation generated by
``lala-repr-code/scripts/sdf2lalas_csv.py``.

The generator turns a 3D structure into a string such as::

    ben,ben,(pyd[N:1]),fur[O:3]  LA()a

Two independent things can go wrong there, and this script checks one of each.

1. Orientation independence (canonicalisation)
----------------------------------------------
Before anything else is computed, ``Mol.align_to_xy_plane`` rotates the molecule
into the xy-plane using the eigenvectors of its inertia tensor. The sign of
those eigenvectors is not fixed: the same molecule can come out mirrored on a
different machine, a different BLAS build, or a different numpy version. A
mirror image is the same molecule flipped over, so the representation must not
change - if it does, the output depends on where it was generated and the
"canonical" representation is not canonical.

Historically it did change, in two ways, both fixed:

* heteroatom positions were numbered in a hardcoded direction whenever the
  chirality label could not fix one (all-linear or symmetric molecules), so
  mirroring turned ``fur[O:3]`` into ``fur[O:1]``;
* the annulation digit at a fork of two end rings inside a branch was hardcoded
  instead of computed from the geometry, so mirroring turned ``A(A())`` into
  ``A(a())``.

The check mirrors each molecule *after* alignment (negating x in the aligned
frame, which is an exact mirror) and requires an identical representation.
Mirroring the raw input instead would not do: the alignment step may undo it.

2. Ring content (chemistry)
---------------------------
Orientation independence says nothing about whether the rings themselves are
right - a wrong ring type is wrong in both orientations. So each molecule's
ring-type counts are compared against the COMPAS feature table, which is the
ground truth here: eleven per-type columns (benzene, pyridine, ... ,
cyclobutadiene) plus a ``rings`` total.

One caveat about that table: for roughly 1.5% of molecules its own columns
contradict each other - the eleven per-type counts sum to one more than its
``rings`` total, always in ``benzene``. Such rows cannot be used to judge the
generator, so they are reported separately ("unusable ground truth") instead of
being counted as failures. Rows whose columns are self-consistent are checked
strictly, including the total ring count.

What this does NOT check
------------------------
That the LALAS string is chemically correct, and that the chosen traversal is
the lexicographically smallest of those with the same LALAS. Both are
properties of the selection rules themselves (see the README); this script only
catches a representation that is orientation-dependent or that disagrees with
the ground-truth ring content.

Usage
-----
    python verification/verify_representation.py                  # 2000 random molecules
    python verification/verify_representation.py --sample 20000
    python verification/verify_representation.py --names C2M021198,C2M000005
    python verification/verify_representation.py --report out.csv # failures as CSV

Only ``charge == 0`` records are used, matching the generator. Molecules with
fewer than three rings are skipped, as the generator skips them too.

Exits 0 when every check passes, 1 otherwise.
"""

from __future__ import annotations

import argparse
import csv
import random
import sys
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LALA_DIR = PROJECT_ROOT / "lala-repr-code"
sys.path.insert(0, str(LALA_DIR))
sys.path.insert(0, str(LALA_DIR / "scripts"))

from xyz2lalas import knotidentifier, pathfinder, chirality, ringclassifier, mol  # noqa: E402
from compas2lalas import iter_sdf  # noqa: E402

DEFAULT_SDF = PROJECT_ROOT / "data" / "compas-2x.sdf"
DEFAULT_FEATURES = PROJECT_ROOT / "data" / "compas-2x.csv"
COVALENCY_FACTOR = 1.3

# Ring-type abbreviation -> column name in the COMPAS feature table.
RING_TYPE_COLUMNS = {
    "ben": "benzene", "pyd": "pyridine", "pyz": "pyrazine", "brn": "borinine",
    "dbrn": "14diborinine", "dhdb": "dhdiborinine", "bor": "borole",
    "pyl": "pyrrole", "fur": "furan", "thi": "thiophene", "cbd": "cyclobutadiene",
}

csv.field_size_limit(min(sys.maxsize, 2_147_483_647))


def representation(atoms, bonds, mirror=False):
    """
    Build the representation exactly as ``sdf2lalas_csv.lalas_representation``
    does. With ``mirror=True`` the molecule is mirrored in the aligned frame
    first, which must not change the result.
    """
    molrepr = mol.Mol([[element, x, y, z] for element, x, y, z in atoms], bonds)
    molrepr.align_to_xy_plane()
    if mirror:
        for atom in molrepr.atoms:
            atom.x = -atom.x

    knots, _ = knotidentifier.identify(molrepr, COVALENCY_FACTOR)
    if len(knots) < 3:
        raise ValueError(f"only {len(knots)} ring(s) identified; need at least 3")

    paths, graph, knotedges = pathfinder.find(knots)
    names_by_index = {
        k.index: ringclassifier.classify_ring(k, molrepr.atoms, COVALENCY_FACTOR)
        for k in knots
    }
    ring_types = ringclassifier.canonical_ring_sequence(
        paths, knotedges, knots, graph, molrepr.atoms, COVALENCY_FACTOR)
    _, augmented_lalas, _, _ = chirality.canonical_lalas_fields(
        paths, knotedges, knots, graph, ring_type_for_idx=names_by_index.get)
    return f"{ring_types} {augmented_lalas}"


def ring_type_counts(representation_string):
    """Count ring types in a representation, ignoring branches and positions."""
    ring_part = representation_string.rsplit(" ", 1)[0].replace("(", "").replace(")", "")
    counts, token, in_brackets = Counter(), [], False
    for char in ring_part + ",":
        if char == "[":
            in_brackets = True
        elif char == "]":
            in_brackets = False
        if char == "," and not in_brackets:
            if token:
                counts["".join(token).split("[", 1)[0]] += 1
            token = []
        else:
            token.append(char)
    return counts


def load_ground_truth(features_csv):
    """``{name: ({ring type: count}, total_rings)}`` for charge-0 molecules."""
    truth = {}
    with open(features_csv, newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            if row.get("charge", "").strip() != "0":
                continue
            truth[row["name"]] = (
                {abbrev: int(row[column] or 0) for abbrev, column in RING_TYPE_COLUMNS.items()},
                int(row["rings"] or 0),
            )
    return truth


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sdf", default=str(DEFAULT_SDF))
    parser.add_argument("--features-csv", default=str(DEFAULT_FEATURES))
    parser.add_argument("--sample", type=int, default=2000,
                        help="How many random molecules to check (default: 2000).")
    parser.add_argument("--seed", type=int, default=0,
                        help="Seed for the random sample, so runs are reproducible.")
    parser.add_argument("--names", help="Comma-separated molecule names; overrides --sample.")
    parser.add_argument("--report", help="Write failing molecules to this CSV.")
    args = parser.parse_args()

    sdf_path, features_path = Path(args.sdf), Path(args.features_csv)
    for path in (sdf_path, features_path):
        if not path.is_file():
            raise SystemExit(f"not found: {path}")

    print(f"# reading ground truth from {features_path}", flush=True)
    truth = load_ground_truth(features_path)
    print(f"# {len(truth)} charge-0 molecules in the feature table", flush=True)

    if args.names:
        targets = {name.strip() for name in args.names.split(",") if name.strip()}
        missing = targets - set(truth)
        if missing:
            raise SystemExit(f"not in the feature table: {sorted(missing)}")
    else:
        targets = set(random.Random(args.seed).sample(sorted(truth), min(args.sample, len(truth))))
    remaining = set(targets)
    print(f"# checking {len(targets)} molecules from {sdf_path}", flush=True)

    checked = skipped = mirror_failures = content_failures = unusable_truth = 0
    failures = []

    for name, data, atoms, bonds in iter_sdf(sdf_path):
        if name not in remaining or data.get("charge", "").strip() != "0":
            continue
        remaining.discard(name)

        try:
            rep = representation(atoms, bonds)
        except ValueError as exc:          # fewer than three rings: generator skips these too
            skipped += 1
            if not remaining:
                break
            continue
        except Exception as exc:           # noqa: BLE001 - any failure is a real failure
            content_failures += 1
            failures.append([name, "error", str(exc), ""])
            if not remaining:
                break
            continue

        checked += 1

        mirrored = representation(atoms, bonds, mirror=True)
        if mirrored != rep:
            mirror_failures += 1
            failures.append([name, "mirror", rep, mirrored])

        expected, expected_total = truth[name]
        if sum(expected.values()) != expected_total:
            unusable_truth += 1
        else:
            counts = ring_type_counts(rep)
            wrong = {abbrev for abbrev in RING_TYPE_COLUMNS
                     if counts.get(abbrev, 0) != expected[abbrev]}
            unknown = set(counts) - set(RING_TYPE_COLUMNS)
            if wrong or unknown or sum(counts.values()) != expected_total:
                content_failures += 1
                detail = f"differs in {sorted(wrong) or sorted(unknown) or ['total rings']}"
                failures.append([name, "ring content", rep, detail])

        if checked % 500 == 0:
            print(f"... {checked} checked", flush=True)
        if not remaining:
            break

    print(f"\nchecked: {checked}   skipped (fewer than 3 rings): {skipped}")
    print(f"mirror-invariant: {checked - mirror_failures}/{checked}")
    print(f"ring content matches ground truth: {checked - unusable_truth - content_failures}"
          f"/{checked - unusable_truth}"
          f"   (skipped {unusable_truth} molecules whose feature-table rows contradict themselves)")
    if remaining:
        print(f"not found in the SDF: {len(remaining)} {sorted(remaining)[:5]}")

    if failures:
        print(f"\nFAILURES: {len(failures)}")
        for row in failures[:10]:
            print(f"  {row[0]} [{row[1]}]\n    {row[2]}\n    {row[3]}")
        if args.report:
            with open(args.report, "w", newline="", encoding="utf-8") as handle:
                writer = csv.writer(handle)
                writer.writerow(["name", "check", "representation", "detail"])
                writer.writerows(failures)
            print(f"\nwrote {len(failures)} failures to {args.report}")
        return 1

    print("\nall checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
