"""
Extract individual molecule geometries from a COMPAS .sdf / .sdf.gz file into
plain xyz files, optionally running the LALAS pipeline on each.

The COMPAS-2 distribution stores all geometries in a single multi-record SDF:
  COMPAS-2/compas-2D.sdf.gz   ~99 MB,  DFT geometries
  COMPAS-2/compas-2x.sdf.gz   ~1 GB,   xTB geometries
This script never loads the whole file - it iterates record-by-record so even
the 1 GB xTB file is fine - and only writes / runs the records you actually
ask for.

Examples (run from the lala-repr-code/ directory, with the venv activated):

  # 1. peek at the file: print the first 10 record titles + atom counts.
  python scripts/compas2lalas.py --sdf "C:/Users/ofree/Desktop/Projects/compas/COMPAS-2/compas-2D.sdf.gz" --list 10

  # 2. extract specific molecules by their SDF title (the 9-char COMPAS name).
  python scripts/compas2lalas.py --sdf "C:/.../compas-2D.sdf.gz" --names TM00001,TM00007

  # 3. extract the first 5 molecules into examples/compas/ (default --out).
  python scripts/compas2lalas.py --sdf "C:/.../compas-2D.sdf.gz" --first 5

  # 4. extract by index range (0-based, end exclusive) and immediately run
  #    the LALAS pipeline on each:
  python scripts/compas2lalas.py --sdf "C:/.../compas-2D.sdf.gz" --range 100:105 --run

The output xyz files use the SDF title as their filename (sanitised), so they
plug straight into  python xyz2lalas.py examples/compas/<TITLE>.xyz.
"""

from __future__ import annotations

import argparse
import gzip
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Iterable, Iterator


SCRIPT_DIR = Path(__file__).resolve().parent
LALA_DIR = SCRIPT_DIR.parent              # lala-repr-code/
PROJECT_ROOT = LALA_DIR.parent            # repo root
DEFAULT_OUT = PROJECT_ROOT / "examples" / "compas"
LALAS_ENTRY = LALA_DIR / "xyz2lalas.py"


# ----------------------------------------------------------------- SDF reader

def _open_sdf(path: Path):
    if str(path).endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, "rt", encoding="utf-8", errors="replace")


_DATA_HEADER = re.compile(r"^>.*<\s*([^>]+?)\s*>")


def iter_sdf(sdf_path: Path) -> Iterator[tuple[str, dict[str, str], list[tuple[str, float, float, float]], list[tuple[int, int]]]]:
    """
    Yield (record_id, data_fields, atoms, bonds) for each record in an SDF
    (V2000) file. record_id is the title-line if non-empty, otherwise the
    value of the 'name' data field, otherwise an autogenerated index.
    data_fields holds all ``> <KEY>\\nvalue`` blocks attached to the record.
    atoms is a list of (element, x, y, z) tuples. bonds is a list of
    (i, j) 0-based atom-index pairs parsed from the SDF bond block (i < j).
    """
    with _open_sdf(sdf_path) as f:
        idx = -1
        while True:
            title = f.readline()
            if not title:
                return
            idx += 1
            title = title.rstrip("\r\n").strip()
            f.readline()                          # software stamp / comment
            f.readline()                          # extra comment / blank
            counts = f.readline()
            if not counts:
                return
            n_atoms = int(counts[0:3])
            n_bonds = int(counts[3:6])

            atoms: list[tuple[str, float, float, float]] = []
            for _ in range(n_atoms):
                line = f.readline()
                # V2000 atom line: x[0:10] y[10:20] z[20:30] sp el[31:34] ...
                x = float(line[0:10])
                y = float(line[10:20])
                z = float(line[20:30])
                el = line[31:34].strip()
                atoms.append((el, x, y, z))

            bonds: list[tuple[int, int]] = []
            for _ in range(n_bonds):
                # V2000 bond line: a1[0:3] a2[3:6] type[6:9] ... (atoms 1-based)
                line = f.readline()
                a1_str = line[0:3].strip()
                a2_str = line[3:6].strip()
                if not (a1_str and a2_str):
                    parts = line.split()
                    if len(parts) < 2:
                        continue
                    a1_str, a2_str = parts[0], parts[1]
                try:
                    a1 = int(a1_str) - 1
                    a2 = int(a2_str) - 1
                except ValueError:
                    continue
                if a1 == a2 or a1 < 0 or a2 < 0 or a1 >= n_atoms or a2 >= n_atoms:
                    continue
                if a1 > a2:
                    a1, a2 = a2, a1
                bonds.append((a1, a2))

            # data block: alternating  >  <KEY>  /  value lines /  blank /  ...
            data: dict[str, str] = {}
            current_key: str | None = None
            current_val: list[str] = []
            while True:
                line = f.readline()
                if not line:
                    if current_key is not None:
                        data[current_key] = "\n".join(current_val).strip()
                    return
                stripped = line.rstrip("\r\n")
                if stripped.strip() == "$$$$":
                    if current_key is not None:
                        data[current_key] = "\n".join(current_val).strip()
                    break
                m = _DATA_HEADER.match(stripped)
                if m:
                    if current_key is not None:
                        data[current_key] = "\n".join(current_val).strip()
                    current_key = m.group(1).strip()
                    current_val = []
                    continue
                if current_key is not None:
                    current_val.append(stripped)

            record_id = title or data.get("name") or f"record_{idx:06d}"
            yield record_id, data, atoms, bonds


# ----------------------------------------------------------------- xyz writer

_SAFE_NAME = re.compile(r"[^A-Za-z0-9_.\-]+")


def _sanitise(name: str) -> str:
    safe = _SAFE_NAME.sub("_", name).strip("_")
    return safe or "molecule"


def write_xyz(path: Path, atoms: list[tuple[str, float, float, float]],
              comment: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"{len(atoms)}\n{comment}\n")
        for el, x, y, z in atoms:
            f.write(f"{el:<3s} {x:14.6f} {y:14.6f} {z:14.6f}\n")


def _xyz_comment(record_id: str, data: dict[str, str]) -> str:
    """Compact one-line description for the xyz comment field."""
    parts = [f"COMPAS {record_id}"]
    for key in ("charge", "formula", "smiles", "energy"):
        if key in data and data[key]:
            parts.append(f"{key}={data[key]}")
    return "  ".join(parts)


def _filename_for(record_id: str, data: dict[str, str]) -> str:
    """Build a unique filename: <name>_chrg<charge>.xyz so the same molecule's
    charge states get distinct files."""
    base = _sanitise(record_id)
    charge = data.get("charge", "").strip()
    if charge:
        return f"{base}_chrg{_sanitise(charge)}.xyz"
    return f"{base}.xyz"


# ------------------------------------------------------------- LALAS runner

def run_lalas(xyz_path: Path) -> int:
    """Invoke xyz2lalas.py on the given xyz and print its output."""
    print(f"--- LALAS for {xyz_path.name} ---", flush=True)
    proc = subprocess.run(
        [sys.executable, str(LALAS_ENTRY), str(xyz_path)],
        cwd=str(LALA_DIR),
        capture_output=True,
        text=True,
    )
    if proc.stdout:
        print(proc.stdout.rstrip("\n"), flush=True)
    if proc.returncode != 0 or proc.stderr:
        print(f"[exit {proc.returncode}]", flush=True)
        if proc.stderr:
            print(proc.stderr.rstrip("\n"), file=sys.stderr, flush=True)
    return proc.returncode


# ------------------------------------------------------------------ selectors

def _selector(args) -> tuple[str, object]:
    """Translate argparse args into a (mode, value) selector tuple."""
    if args.list is not None:
        return "list", args.list
    if args.names:
        return "names", set(n.strip() for n in args.names.split(",") if n.strip())
    if args.first is not None:
        return "first", args.first
    if args.range:
        a, _, b = args.range.partition(":")
        return "range", (int(a or 0), int(b) if b else None)
    raise SystemExit("Pick one of --list / --names / --first / --range.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract a subset of COMPAS molecule geometries to xyz "
                    "and (optionally) run xyz2lalas on each.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--sdf", required=True,
                        help="Path to compas-2D.sdf.gz or compas-2x.sdf.gz "
                             "(or any plain .sdf).")
    parser.add_argument("--out", default=str(DEFAULT_OUT),
                        help=f"Output directory for xyz files "
                             f"(default: {DEFAULT_OUT}).")
    parser.add_argument("--run", action="store_true",
                        help="After writing each xyz, run xyz2lalas.py on it.")

    sel = parser.add_argument_group("selection (pick one)")
    sel.add_argument("--list", type=int, nargs="?", const=10, default=None,
                     metavar="N",
                     help="Don't extract anything; just print the first N "
                          "titles (default 10) and their atom counts.")
    sel.add_argument("--names", type=str,
                     help="Comma-separated SDF titles to extract "
                          "(e.g. TM00001,TM00007).")
    sel.add_argument("--first", type=int,
                     help="Extract the first N records.")
    sel.add_argument("--range", type=str, metavar="A:B",
                     help="Extract records [A, B) by 0-based index "
                          "(B optional = to end).")
    args = parser.parse_args()

    sdf_path = Path(args.sdf).expanduser().resolve()
    if not sdf_path.is_file():
        raise SystemExit(f"SDF not found: {sdf_path}")
    out_dir = Path(args.out).expanduser().resolve()
    mode, value = _selector(args)

    if mode == "list":
        print(f"# first {value} records of {sdf_path.name}:")
        for i, (record_id, data, atoms, _bonds) in enumerate(iter_sdf(sdf_path)):
            if i >= value:
                break
            elements = sorted({a[0] for a in atoms})
            charge = data.get("charge", "?")
            print(f"  [{i:5d}] {record_id:<12s} chrg={charge:>3s}  "
                  f"natoms={len(atoms):3d}  elements={','.join(elements)}")
        return

    extracted: list[Path] = []
    if mode == "names":
        wanted: set = set(value)
        for record_id, data, atoms, _bonds in iter_sdf(sdf_path):
            if record_id in wanted:
                xyz = out_dir / _filename_for(record_id, data)
                write_xyz(xyz, atoms, comment=_xyz_comment(record_id, data))
                extracted.append(xyz)
                # do NOT discard: same name may have several charge variants

    elif mode == "first":
        n = int(value)
        for i, (record_id, data, atoms, _bonds) in enumerate(iter_sdf(sdf_path)):
            if i >= n:
                break
            xyz = out_dir / _filename_for(record_id, data)
            write_xyz(xyz, atoms, comment=_xyz_comment(record_id, data))
            extracted.append(xyz)

    elif mode == "range":
        a, b = value
        for i, (record_id, data, atoms, _bonds) in enumerate(iter_sdf(sdf_path)):
            if i < a:
                continue
            if b is not None and i >= b:
                break
            xyz = out_dir / _filename_for(record_id, data)
            write_xyz(xyz, atoms, comment=_xyz_comment(record_id, data))
            extracted.append(xyz)

    print(f"# wrote {len(extracted)} xyz file(s) to {out_dir}", flush=True)
    for p in extracted:
        print(f"  {p}", flush=True)

    if args.run and extracted:
        print(flush=True)
        for xyz in extracted:
            run_lalas(xyz)
            print(flush=True)


if __name__ == "__main__":
    main()
