import os.path
import re

from .const import __ATOM_LIST__

from . import mol





def str_atom(_atom):
    """
    str_atom(_atom: int) -> atom: str

    Convert integer atom to string atom.

    in:
    _atom: Integer with the atomic number.

    out:
    atom: String with the atomic element.

    """

    atom = __ATOM_LIST__[_atom - 1]
    return atom


def load(_path):
    """
    load(_path: str) -> molrepr: Mol

    Check input file extension and call appropriate load function. Return Mol Object 
    generated by the load function.

    in:
    _path: String with the path of the input file.

    out:
    molrepr: Mol Object containing the molecular information (coordinates and elements).

    """

    filetype = determine_filetype(_path)
    loaders = {
        'xyz': load_xyz,
        'in': load_gaussian,
        'sdf': load_sdf,
    }

    if filetype not in loaders:
        supported = ", ".join(sorted(loaders))
        raise ValueError(f"Unsupported input file type '{filetype}'. Supported types: {supported}")

    return loaders[filetype](_path)


def iter_sdf(_path):
    """
    Yield Mol objects for each molecule record in an SDF file.
    """
    with open(_path, "r", encoding="utf-8") as file:
        record = []
        for line in file:
            if line.strip() == "$$$$":
                if record:
                    yield _mol_from_sdf_record(record)
                    record = []
                continue
            record.append(line.rstrip("\n"))

        # Support files without a trailing "$$$$".
        if record:
            yield _mol_from_sdf_record(record)


def determine_filetype(_path):
    """
    determine_filetype(_path: str) -> filetype: str

    Return the extension of the input file.

    in:
    _path: String with the path of the input file.

    out:
    filetype: String containing the extentsion of the input file.

    """

    filetype = os.path.splitext(_path)[1][1:].lower()
    return filetype


def load_xyz(_path):
    """
    load_xyz(_path: str) -> molrepr: Mol

    Load molecule from an XYZ input file and initialize a Mol Object for it.

    in:
    _path: String with the path of the input file.

    out:
    molrepr: Mol Object containing the molecular information (coordinates and elements).

    """

    molrepr = []
    with open(_path, "r") as file:
        for line_number, line in enumerate(file):
            if line_number > 1:
                atomic_symbol, x, y, z = line.split()
                if not atomic_symbol.isalpha():
                    atomic_symbol = int(atomic_symbol)
                    atomic_symbol = str_atom(atomic_symbol)
                molrepr.append([atomic_symbol.capitalize(), float(x), float(y), float(z)])

    molrepr = mol.Mol(molrepr)
    return molrepr


def load_gaussian(_path):
    """
    load_gaussian(_path: str) -> molrepr: Mol

    Load molecule from an gaussian input file and initialize a Mol Object for it.

    in:
    _path: String with the path of the input file.

    out:
    molrepr: Mol Object containing the molecular information (coordinates and elements).
    
    """
    
    molrepr = []
    data = ""
    blank_line_regex = r"(?:\r?\n){2,}" # match multiple (at least one) empty line
    
    with open(_path, "r") as file:
        for line in file:
            if line.startswith('#') or line.startswith('%'): # remove link0 and route section
                continue
            else:
                data += line
    data = re.split(blank_line_regex, data.strip()) # remove leading and trailing whitespace and then split along newlines

    # data[0] should now be the title field
    # data[1] should be the coordinates
    lines = data[1].splitlines()[1:]

    for line in lines:
        atomic_symbol, x, y, z = line.split()
        if not atomic_symbol.isalpha():
            atomic_symbol = int(atomic_symbol)
            atomic_symbol = str_atom(atomic_symbol)
        molrepr.append([atomic_symbol.capitalize(), float(x), float(y), float(z)])

    molrepr = mol.Mol(molrepr)
    return molrepr


def load_sdf(_path):
    """
    load_sdf(_path: str) -> molrepr: Mol

    Load the first molecule from an SDF/Molfile input and initialize a Mol
    Object for it.
    """

    with open(_path, "r", encoding="utf-8") as file:
        record = []
        for line in file:
            if line.strip() == "$$$$":
                break
            record.append(line.rstrip("\n"))

    if not record:
        raise ValueError("Invalid SDF: no molecule records found.")

    return _mol_from_sdf_record(record)


def _mol_from_sdf_record(record):
    if len(record) < 4:
        raise ValueError("Invalid SDF: missing molfile header/counts lines.")

    counts_line = record[3]
    atom_count_str = counts_line[:3].strip()
    bond_count_str = counts_line[3:6].strip()
    if not atom_count_str:
        parts = counts_line.split()
        if not parts:
            raise ValueError("Invalid SDF: unable to read atom count from counts line.")
        atom_count_str = parts[0]
        bond_count_str = parts[1] if len(parts) > 1 else "0"

    try:
        atom_count = int(atom_count_str)
        bond_count = int(bond_count_str) if bond_count_str else 0
    except ValueError as exc:
        raise ValueError("Invalid SDF: atom/bond count is not an integer.") from exc

    atom_start = 4
    atom_end = atom_start + atom_count
    bond_start = atom_end
    bond_end = bond_start + bond_count
    if len(record) < atom_end:
        raise ValueError("Invalid SDF: atom block shorter than declared atom count.")

    molrepr = []
    for line in record[atom_start:atom_end]:
        x_str = line[0:10].strip()
        y_str = line[10:20].strip()
        z_str = line[20:30].strip()
        symbol = line[31:34].strip()

        if not (x_str and y_str and z_str and symbol):
            parts = line.split()
            if len(parts) < 4:
                raise ValueError("Invalid SDF: malformed atom line.")
            x_str, y_str, z_str, symbol = parts[:4]

        if not symbol.isalpha():
            symbol = str_atom(int(symbol))

        molrepr.append([symbol.capitalize(), float(x_str), float(y_str), float(z_str)])

    bonds = _parse_sdf_bond_block(record[bond_start:bond_end], atom_count)

    return mol.Mol(molrepr, bonds)


def _parse_sdf_bond_block(bond_lines, atom_count):
    """
    Parse a V2000 SDF bond block. Each line has fixed-width fields
    ``aaabbbttt...`` where ``aaa`` and ``bbb`` are 1-based atom indices and
    ``ttt`` is the bond type (ignored - only connectivity is used).
    Returns a list of ``(i, j)`` pairs (0-based, i < j) with duplicates
    and self-loops dropped. Lines that cannot be parsed are skipped.
    """
    bonds = []
    for line in bond_lines:
        a1_str = line[0:3].strip()
        a2_str = line[3:6].strip()
        if not (a1_str and a2_str):
            parts = line.split()
            if len(parts) < 2:
                continue
            a1_str, a2_str = parts[0], parts[1]
        try:
            a1 = int(a1_str) - 1
            a2 = int(a2_str) - 1
        except ValueError:
            continue
        if a1 == a2 or a1 < 0 or a2 < 0 or a1 >= atom_count or a2 >= atom_count:
            continue
        bonds.append((a1, a2))
    return bonds
